<a href="https://colab.research.google.com/github/pavan18b/ML-23AG1A66D5/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np


In [2]:

# create a list named list1
list1 = [2, 4, 6, 8]

# create numpy array using list1
array1 = np.array(list1)

print(array1)

[2 4 6 8]


In [3]:

# create numpy array using a list
array1 = np.array([2, 4, 6, 8])
print(array1)

[2 4 6 8]


In [4]:
# create a 2D array with 2 rows and 4 columns
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
# create a 3D array with 2 "slices", each of 3 rows and 4 columns
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [6]:
# create an array of integers
array1 = np.array([2, 4, 6])

# check the data type of array1
print(array1.dtype)

int64


In [7]:
print(array1.ndim)

1


In [8]:
print(array1.size)

3


In [9]:

array1 = np.array([[1, 2, 3],
                [6, 7, 8]])

# return a tuple that gives size of array in each dimension
print(array1.shape)

(2, 3)


In [10]:
# create a default 1-D array of integers
array1 = np.array([6, 7, 8, 10, 13])

# create a 1-D array of 32-bit integers
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)

# use of itemsize to determine size of each array element of array1 and array2
print(array1.itemsize)
print(array2.itemsize)

8
4


In [11]:

array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])

# print memory address of array1's and array2's data
print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x7bdb63438400>
Data of array2 is:  <memory at 0x7bdb52733030>


In [12]:
array1 = np.array([1, 3, 5, 7, 9])

# access numpy elements using index
print(array1[0])
print(array1[2])
print(array1[4])

1
5
9


In [13]:

array1[1]=10
print(array1)

[ 1 10  5  7  9]


In [14]:

# create a 2D array
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])


# access the element at the second row and fourth column
element1 = array1[1, 3]  # returns 15
print("4th Element at 2nd Row:",element1)

# access the element at the first row and second column
element2 = array1[0, 1]  # returns 3
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 15
2nd Element at First Row: 3


In [15]:
# create a 1D array with 5 elements
array1 = np.array([1, 2, 3, 4, 5])

# calculate the median
median = np.median(array1)

print(median)


3.0


In [16]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the mean of marks
mean_marks = np.mean(marks)

print(mean_marks)


77.2


In [17]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.std(marks)
print(std_marks)

6.368673331236263


In [19]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.percentile(marks,50)
print(std_marks)

78.0


In [20]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.min(marks)
print(std_marks)

66


In [21]:

# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.max(marks)
print(std_marks)

85
